title: Ojas Sanghi
subtitle: #A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
#  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Ojas Sanghi
author_bio: Hi! I'm Ojas Sanghi. # my name is John Doe. I built this site using devlopr-jekyll :D
author_email: "ojas.sanghi@protonmail.com"
author_location: Arizona, USA
author_website_url: "https://ojas-sanghi.me"

# Activities
activities:
  - title: Worked on various Google Products
    location_date: AAAAAAAAAAAAAAAAAAAAAAA
    description: :)))
    company_logo: google.png

  - title: Azure stuff
    location_date: microsoft
    description: asdasdadas
    company_logo: microsoft.png

# Projects
author_project_details:
  - project_thumbnail: boomerang-bonanza.png
    project_title: Boomerang Bonanza
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in

  - project_thumbnail: chukwas-labyrinth.PNG
    project_title: Chgukws's Labyrinth
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
  
  - project_thumbnail: penguin-dynamics.PNG
    project_title: Penguin Dynamics
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com

# social links
github_username: ojas-sanghi
pseudonym_github_username: Sajo8

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
